---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book-container
          image: devops1117/pythonlib:book_v14
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book
  ports:
    - port: 5002
      targetPort: 5002
  type: ClusterIP
  template:
    spec:
      containers:
        - image: devops1117/pythonlib:book_v14
