---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-deployment
  labels:
    app: borrow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: borrow
  template:
    metadata:
      labels:
        app: borrow
    spec:
      containers:
        - name: borrow-container
          image: devops1117/pythonlib:borrow_v16
          ports:
            - containerPort: 5003
